# -*- coding: utf-8 -*-
"""TALLER_CON_COLORES_DANIELAGONZALEZ_LUISABAYONA_SARADIAZ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QIGvOqH3pojwsdpGoTlcP6aqNWrLMMaA
"""

#CLASES
#GALLETA SARA
#ROBOT DANIELA
#PERRO LUISA
#ATRIBUTOS G
#ATRIBUTOS R
#ATRIBUTOS P
class galleta:
  def __init__(self, name, age, sabor, color, tamano):
    self.name = name
    self.age = age
    self.sabor = sabor
    self.color = color
    self.tamano = tamano

    def decorarse(self):
      print("fiu fiu")
    def hornearse(self):
      print("fuashh")
    def comerse(self):
      print("ñam ñam")
    def romperse(self):
      print("crack")
    def hablar(self):
      print("blaaaa")


class robot:
  def __init__(self, name, tamano, material, funcion, bateria):
    self.name = name
    self.tamano = tamano
    self.material = material
    self.funcion = funcion
    self.bateria = bateria

    def cargar(self):
      print("piiiiii")
    def moverse(self):
      print("wiiii")
    def hablar(self):
      print("bla bla bla")
    def apagar(self):
      print("off")
    def encender(self):
      print("on")


class perro:
  def __init__(self, name, age, raza, color, tamano):
    self.name = name
    self.age = age
    self.raza = raza
    self.color = color
    self.tamano = tamano

    def comer(self):
      print("ñam ñam")
    def correr(self):
      print("pum pum pum")
    def ladrar(self):
      print("wuf wuf")
    def dormir(self):
      print("zzzzzz")
    def jugar(self):
      print("wahoo!!")

g1= galleta('erick', 2, 'chocolate', 'negro', 'pequeño')

print(g1.name)
print(g1.age)
print(g1.sabor)
print(g1.color)
print(g1.tamano)
print()

g2= galleta('taylor', 5, 'vainilla', 'beige', 'pequeño')

print(g2.name)
print(g2.age)
print(g2.sabor)
print(g2.color)
print(g2.tamano)
print()
g3= galleta('madison', 1, 'fresa', 'rosado', 'grande')

print(g3.name)
print(g3.age)
print(g3.sabor)
print(g3.color)
print(g3.tamano)
print()
r1= robot('billie', 'pequeño', 'acero', 'limpieza', 100)

print(r1.name)
print(r1.tamano)
print(r1.material)
print(r1.funcion)
print(r1.bateria)
print()
r2= robot('frank', 'mediano', 'metal', 'canta', 80)

print(r1.name)
print(r1.tamano)
print(r1.material)
print(r1.funcion)
print(r1.bateria)
print()
r3= robot('billie', 'grande', 'madera', 'baila', 55)

print(r1.name)
print(r1.tamano)
print(r1.material)
print(r1.funcion)
print(r1.bateria)
print()
p1= perro('winter', 2, 'cocker_spaniel', 'dorado', 'mediano')

print(p1.name)
print(p1.age)
print(p1.raza)
print(p1.color)
print(p1.tamano)
print()
p2= perro('reiji', 4, 'golden_retriever', 'rubio', 'grande')

print(p2.name)
print(p2.age)
print(p2.raza)
print(p2.color)
print(p2.tamano)
print()
p3= perro('presley', 1, 'labradoodle', 'negro', 'mediano')

print(p3.name)
print(p3.age)
print(p3.raza)
print(p3.color)
print(p3.tamano)
print()